import "./globals.css";
import Header from "./(component)/Header";
import Footer from "./(component)/Footer";
import { Providers } from "./Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
  
    >
     
      <body >
        <Header/>
          <Providers>
            {children}
          </Providers>
      <Footer/>
      </body>
    </html>
  );
}
